### ISSUE TITLE
Printer not following delimiter space

### ISSUE THREAD

**Issue by IamMU** [IamMU/Fancy-Print#20]

**Comment by Aditi-1709** [comment]
Can you elaborate on your issue ?

**Comment by IamMU** [comment]
@Aditi-1709 thanks for showing interest, but I'm taking the repo off radar for a few months to redo everything with a more robust foundation.
You can read about it in the readme

**Comment by IamMU** [comment]
Still looking for someone to do #8 though. Mention me there if you are interested
