### ISSUE TITLE
Add option for color using color tags

### ISSUE THREAD

**Issue by IamMU** [IamMU/Fancy-Print#3]
Examples:
printer.print("\<r>Red \<b>Blue", align="left")
Function to edit:
printer.print()

**Comment by achiverram28** [comment]
I want to work on this

**Comment by IamMU** [comment]
Sure go ahead.
Tips:
   - create a function named something like convert_tags_to_colors(input: str) -> str:
   - execute the function at the beginning of the printer.print() function

**Comment by achiverram28** [comment]
ok. Could you give me a bit more detailing , so that I can work on in a  clear manner

**Comment by IamMU** [comment]
Okay so there is a print() method in the Printer class. You don't need to worry about the config parameter, just use the text/input parameter and do something like text = convert_tags_to_color(text), and create the function for that. In the function replace the color tags with the respective codes in COLORS (from the constants file in helpers package).

**Comment by achiverram28** [comment]
Actually there is an error in ur documentation.
printer.print("This is some text in the center",**PrinterConfig**(align=Align.CENTER, blank_character=" ", left_delimiter=True, right_delimiter=True, back_separator=True,front_separator=True)), should be changed to 
printer.print("This is some text in the center",**PrintConfig**(align=Align.CENTER, blank_character=" ", left_delimiter=True, right_delimiter=True, back_separator=True,front_separator=True))
as PrinterConfig doesn't not have align

**Comment by IamMU** [comment]
Needs correct file structure for re-merging.
