### ISSUE TITLE
Add logger function

### ISSUE THREAD

**Issue by IamMU** [IamMU/Fancy-Print#4]
Add a logger function that utilizes self.pretty_print(), and makes it easy for one to log quickly without making it messy.
Example:
\--------------------------------------------
|  [ LEVEL ] MSG****************** |
|  \*\*\*\*[ LEVEL ] MSG************** |
|  \********[ Hierarchy#2] MSG***** |
\-------------------------------------------

**Comment by marvhus** [comment]
I'll look into it
