### ISSUE TITLE
Pass Config as an object for simplicity 

### ISSUE THREAD

**Issue by ahmedheltaher** [IamMU/Fancy-Print#6]

**Comment by IamMU** [comment]
You mean for customizing the printer?

**Comment by ahmedheltaher** [comment]
Yes, We can use `pydantic` to make it more solid in term of typing

**Comment by IamMU** [comment]
Ah, if you think you can do it, go ahead. I'll assign you in a second.

**Comment by ahmedheltaher** [comment]
Yes, I think i can handle it

**Comment by IamMU** [comment]
@ahmedheltaher changes in main file, be sure to pull it before working!!
