### ISSUE TITLE
Create CODE_OF_CONDUCT.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by marvhus** [IamMU/Fancy-Print#8]
TODO:
- [ ] Create CONTRIBUTING.md
- [ ] Create CODE_OF_CONDUCT.md

**Comment by IamMU** [comment]
pretty busy right now to do them myself, would be very helpful if you could make them :smile:

**Comment by goodchai0** [comment]
Please assign this to me under hacktoberfest 2022. @IamMU

**Comment by IamMU** [comment]
@goodchai0 it's already assigned to someone.

**Comment by goodchai0** [comment]
Okay. Please assign it to me, if he don't response.

**Comment by IamMU** [comment]
@goodchai0 free to do it?

**Comment by Akshun-01** [comment]
could you please elaborate on this issue?  @IamMU 
I am free to take work on this issue, just asking if you have any guidelines for writing these docs.

**Comment by goodchai0** [comment]
> @goodchai0 free to do it?

Yes, assign it to me

**Comment by IamMU** [comment]
@Akshun-01 basically it should be stated that NO ONE can change file structure like deleting src and creating some other directory. NO PR will be accepted unless assigned in issues. New issues are welcome.
This is for CoC: Follow PEP-8 (idk what it's called exactly). New code regions are to be commented as:
#######
\# Name #
#######
Uncommented code will not be merged. Over commented code can be merged but is not expected.
Changing major things are to be discussed first.
All functions that are not of use for end-use are to be marked private (adding the __ before the function)

**Comment by IamMU** [comment]
You can take other project's Contributing.md and CoCs as references. DO NOT COPY/PASTE!

**Comment by IamMU** [comment]
Also add something like:
  PRs won't be accepted unless thoroughly tested and explained what one did and also screenshots ought to be sent in the pr

**Comment by Akshun-01** [comment]
Ok got it ...will start working on it by today
